from __future__ import annotations

import argparse
import os
from dataclasses import dataclass

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


@dataclass(frozen=True)
class PlotStyle:
    figure_face: str = "#fbf8f6"
    axes_face: str = "#f5f2ef"
    grid_color: str = "#ddd7d2"
    spine_color: str = "#d8c8f6"
    title_color: str = "#48424f"
    text_color: str = "#5f5968"
    fixed_line: str = "#2c7fb8"
    fixed_fill: str = "#93c4eb"
    rl_line: str = "#d94841"
    rl_fill: str = "#f0a6a0"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a styled swarm-size sweep figure from an existing APSO/RL-APSO CSV."
    )
    parser.add_argument(
        "--csv-path",
        type=str,
        default="rl_vs_fixed_fixedsource_swarm_sweep.csv",
        help="Path to the per-run sweep CSV generated by verify_improvement.py",
    )
    parser.add_argument(
        "--output-path",
        type=str,
        default="results/apso_swarm_sweep_styled.png",
        help="Path for the styled output figure",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="APSO vs RL-APSO Across Swarm Sizes",
        help="Figure title",
    )
    parser.add_argument(
        "--subtitle",
        type=str,
        default="mean curves with +/- 1 standard deviation bands",
        help="Figure subtitle",
    )
    return parser.parse_args()


def _resolve_csv_path(csv_path: str) -> str:
    candidates = [
        csv_path,
        os.path.join(os.getcwd(), csv_path),
        os.path.join(os.path.dirname(__file__), csv_path),
        os.path.join(os.path.dirname(os.path.dirname(__file__)), csv_path),
    ]

    for candidate in candidates:
        if os.path.exists(candidate):
            return os.path.abspath(candidate)

    raise FileNotFoundError(f"Could not find CSV file: {csv_path}")


def _load_and_validate(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    required = {"n_particles", "run", "Ts", "I", "SD", "Success", "Type"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"CSV is missing required columns: {sorted(missing)}")

    df = df.copy()
    df["Type"] = df["Type"].replace({"Fixed": "APSO", "RL": "RL-APSO"})
    return df


def _aggregate_metric(df: pd.DataFrame, metric: str) -> pd.DataFrame:
    grouped = (
        df.groupby(["n_particles", "Type"], as_index=False)[metric]
        .agg(mean="mean", std="std", count="count")
        .sort_values(["Type", "n_particles"])
    )
    grouped["std"] = grouped["std"].fillna(0.0)
    return grouped


def _apply_axes_style(ax: plt.Axes, style: PlotStyle) -> None:
    ax.set_facecolor(style.axes_face)
    ax.grid(True, color=style.grid_color, linewidth=0.8, alpha=0.6)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_color(style.spine_color)
        spine.set_linewidth(1.15)
    ax.tick_params(colors=style.text_color, labelsize=9)


def _plot_metric(ax: plt.Axes, grouped: pd.DataFrame, metric: str, ylabel: str, title: str, style: PlotStyle) -> None:
    series_meta = {
        "APSO": (style.fixed_line, style.fixed_fill, "APSO", "o"),
        "RL-APSO": (style.rl_line, style.rl_fill, "RL-APSO", "o"),
    }

    for method, (line_color, fill_color, label, marker) in series_meta.items():
        subset = grouped[grouped["Type"] == method].sort_values("n_particles")
        if subset.empty:
            continue

        x = subset["n_particles"].to_numpy(dtype=float)
        mean = subset["mean"].to_numpy(dtype=float)
        std = subset["std"].to_numpy(dtype=float)

        ax.fill_between(x, mean - std, mean + std, color=fill_color, alpha=0.30, linewidth=0)
        ax.plot(
            x,
            mean,
            color=line_color,
            linewidth=1.8,
            marker=marker,
            markersize=3.2,
            label=label,
        )

    ax.set_title(title, fontsize=10, color=style.title_color, pad=8)
    ax.set_ylabel(ylabel, fontsize=10, color=style.text_color)


def render_figure(df: pd.DataFrame, output_path: str, title: str, subtitle: str) -> None:
    style = PlotStyle()
    metrics = [
        ("Ts", "Source Seeking Time Ts (s)", "Average Source Seeking Time vs Swarm Size"),
        ("I", "Iterations", "Average Number of Iterations vs Swarm Size"),
        ("SD", "Swarm Distance", "Average Swarm Distance vs Swarm Size"),
    ]

    fig, axes = plt.subplots(3, 1, figsize=(12.0, 12.6), sharex=True)
    fig.patch.set_facecolor(style.figure_face)
    fig.patch.set_edgecolor(style.spine_color)
    fig.patch.set_linewidth(2.2)

    run_count = int(df.groupby(["n_particles", "Type"])["run"].nunique().min())
    max_iter = int(df["I"].max())

    for ax, (metric, ylabel, panel_title) in zip(axes, metrics):
        grouped = _aggregate_metric(df, metric)
        _apply_axes_style(ax, style)
        _plot_metric(ax, grouped, metric, ylabel, panel_title, style)

    axes[0].legend(loc="upper left", frameon=True, facecolor="#ffffff", edgecolor=style.spine_color, fontsize=8)
    axes[-1].set_xlabel("Swarm Size", fontsize=10, color=style.text_color)

    all_sizes = np.sort(df["n_particles"].unique())
    axes[-1].set_xticks(all_sizes)
    axes[-1].set_xlim(all_sizes.min(), all_sizes.max())

    fig.suptitle(title, fontsize=14, color=style.title_color, y=0.982, fontweight="semibold")
    fig.text(
        0.5,
        0.958,
        f"runs per size = {run_count}, max_iter = {max_iter}, area = 100.0 x 100.0\n{subtitle}",
        ha="center",
        va="top",
        fontsize=9,
        color=style.text_color,
    )

    plt.subplots_adjust(top=0.92, hspace=0.24, left=0.09, right=0.985, bottom=0.07)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)


def main() -> None:
    args = parse_args()
    csv_path = _resolve_csv_path(args.csv_path)
    df = _load_and_validate(csv_path)
    render_figure(df, output_path=args.output_path, title=args.title, subtitle=args.subtitle)
    print(f"Saved styled figure to {args.output_path}")


if __name__ == "__main__":
    main()